# configuration of mcp port
quarkus.http.port=8081

# metadata
quarkus.mcp.server.server-info.name=Travel Booking Tools Service
quarkus.mcp.server.server-info.version=1.0.0

# show json-rcp for each request
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=2000